server:
  port: 9000

spring:
  security:
    user:
      name: user
      password: 1234
  datasource:
    url: jdbc:mysql://localhost:3306/faddy_db
    username: root
    password: agh@p970314
    jpa:
      hibernate:
        ddl-auto: update
  mail: # google mail authentication initial setting
    host: smtp.gmail.com
    port: 587
    username: travelwithme.mail@gmail.com
    password: puofrxedultxqtul
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 300000  # 5분