server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/faddy_db?serverTimezone=Asia/Seoul
    username: root
    password: agh@p970314
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  security:
    user:
      name: user
      password: 1234

  #redis metadata
  redis:
    host: localhost
    port: 6379


  # google mail & naver mail authentication initial setting
gmail:
  host: smtp.gmail.com
  port: 587
  username: agh0314@gmail.com
  password: fxxovgvpalqutsuq
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
      ssl:
        trust: smtp.gmail.com
        protocols: TLSv1.2
  auth-code-expiration-millis: 180000  # 3분

naver:
  host: smtp.naver.com
  port: 465
  username: agh0314
  password: agh@p970314
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
        ssl:
          trust: smtp.naver.com
          protocols: TLSv1.2

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  secret: ZmFkZHkgaXMgYmVzdCBmYXNoaW9uIHNoYXJlIGNvbW11bml0eSEgcGxheSB0aGUgbXVzaWMhIO2MqOuUlOuKlCDrsqDsiqTtirjslbwh