server:
  port: 9000

spring:
  security:
    user:
      name: user
      password: 1234
  datasource:
    url: jdbc:mysql://localhost:3306/faddy_db
    username: root
    password: agh@p970314
    jpa:
      hibernate:
        ddl-auto: update
